FROM mcr.microsoft.com/dotnet/core/sdk:3.1

EXPOSE 9092

WORKDIR /app 

COPY dotnetKafkaConsumer ./

RUN dotnet restore

COPY . ./

RUN dotnet publish -c Release -o out

ENTRYPOINT ["dotnet", "out/dotnetKafkaConsumer.dll"]
